using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Opex.Models
{
    public class TblMembers
    {
        public int MemberId { get; set; }
        public int? OldMemberId { get; set; }
        public int? کدیکتا { get; set; }
        public int? کداستان { get; set; }
        public int? کدشهرستان { get; set; }
        public string ناماستان { get; set; }
        public string نامشهرستان { get; set; }
        public string کداتحادیه { get; set; }
        public string ناماتحادیه { get; set; }
        public string وضعیتپرونده { get; set; }
        public string نوعپروانه { get; set; }
        public string شمارهپروانهکسب { get; set; }
        public string تاریخصدور { get; set; }
        public string شمارهدرخواست { get; set; }
        public string تاریخدرخواست { get; set; }
        public string مرحلهدرخواست { get; set; }
        public string ملاحضاتدرخواست { get; set; }
        public string تاریخانقضاء { get; set; }
        public string تاریختمدید { get; set; }
        public int? درجهصنفی { get; set; }
        public string علترددرخواست { get; set; }
        public string شمارهعضویت { get; set; }
        public string شمارهبایگانی { get; set; }
        public string نوعفعالیت { get; set; }
        public string مسلسلجدید { get; set; }
        public string مسلسلقدیم { get; set; }
        public string شمارهتاییداماکن { get; set; }
        public string تاریختاییداماکن { get; set; }
        public string جنسیت { get; set; }
       // [Required(ErrorMessage = "نام را وارد کنید.")]
        public string نام { get; set; }
        public string تاهل { get; set; }
       // [Required(ErrorMessage = "نام خانوادگی را وارد کنید.")]
        public string نامخانوادگی { get; set; }
        public string نامپدر { get; set; }
        public string کدملی { get; set; }
        public string شمارهشناسنامه { get; set; }
        public string مسلسلشناسنامه { get; set; }
        public string تاریخصدورشناسنامه { get; set; }
        public string محلصدورشناسنامه { get; set; }
        public string تاریختولد { get; set; }
        public string محلتولد { get; set; }
        public string بخش { get; set; }
        public string ملیت { get; set; }
        public bool? ایثارگر { get; set; }
        public bool? موقت { get; set; }
        public string روستا { get; set; }
        public bool? ولایت { get; set; }
        public string صادره { get; set; }
        public string موافقتنامه { get; set; }
       // [Required(ErrorMessage = "کدپستی را وارد کنید.")]
        public string کدپستی { get; set; }
        public string آدرس { get; set; }
        public string پلاکآبی { get; set; }
        public string پلاکثبتی { get; set; }
        public string وضعیتاستقرار { get; set; }
        public string محلاستقرار { get; set; }
        public bool? حدودصنفی { get; set; }
        public short? فاصلهصنفی { get; set; }
        public string جهتصنفی { get; set; }
       // [Required(ErrorMessage = "کمیسیون تخصصی اصلی را انتخاب کنید.")]
        public string رسته { get; set; }
        public string کدرسته { get; set; }
        public string شناسهصنفی { get; set; }
        public string تحصیلات { get; set; }
        public string دین { get; set; }
        public string عنوانواحدصنفی { get; set; }
        public string سالتاسیس { get; set; }
        public string تعدادکارکنان { get; set; }
        public string تحتتکفل { get; set; }
        public int? تعدادشریک { get; set; }
        public string وضعیتتملک { get; set; }
        public string وضعیتسند { get; set; }
        public string مساحت { get; set; }
        public string منطقه { get; set; }
        public string محله { get; set; }
        public string تلفنمغازه { get; set; }
        public string فکسمغازه { get; set; }
        public string تلفنمنزل { get; set; }
        public string تلفنهمراه { get; set; }
        public string تلفنمنزلمباشر { get; set; }
        public string فکسمباشر { get; set; }
        public string همراهمباشر { get; set; }
        public string علتابطالپرونده { get; set; }
        public string تاریخابطالپرونده { get; set; }
        public string تاریخفوت { get; set; }
        public string تاریخشناسایی { get; set; }
        public string مرکزشناسایی { get; set; }
        public string ملاحضاتشناسایی { get; set; }
        public string مشارکت { get; set; }
        public short? باب { get; set; }
        public short? دهنه { get; set; }
        public short? دانگ { get; set; }
        public short? کلسهم { get; set; }
        public short? سهم { get; set; }
        public string حوزهمالیاتی { get; set; }
        public string حوزهبیمه { get; set; }
        public string حوزهکلانتری { get; set; }
        public string نامشرکت { get; set; }
        public string شمارهثبتشرکت { get; set; }
        public string تاریخثبتشرکت { get; set; }
        public int? مبلغتمبر { get; set; }
        public string شمارهتمبر { get; set; }
        public string تاریختمبر { get; set; }
        public string وضعیتانتقال { get; set; }
        public string ناماتحادیهقبلی { get; set; }
        public string شمارهپروانهقبلی { get; set; }
        public string تاریخپروانهقبلی { get; set; }
        public string آدرسمنزل { get; set; }
        public string کدپستیمنزل { get; set; }
        public string جنسیتمباشر { get; set; }
        public string ناممباشر { get; set; }
        public string نامپدرمباشر { get; set; }
        public string شناسنامهمباشر { get; set; }
        public string مسلسلمباشر { get; set; }
        public string تاریختولدمباشر { get; set; }
        public string محلتولدمباشر { get; set; }
        public string محلصدورمباشر { get; set; }
        public string تاریخصدورمباشر { get; set; }
        public string تاهلمباشر { get; set; }
        public byte? تعدادتکفلمباشر { get; set; }
        public string شمارهکارتمباشر { get; set; }
        public string تاریخصدورکارتمباشر { get; set; }
        public string تاریخابطالکارتمباشر { get; set; }
        public string شمارهمسلسلمباشر { get; set; }
        public string کدملیمباشر { get; set; }
        public string آدرسمباشر { get; set; }
        public string کدپستیمباشر { get; set; }
        public string تحصیلاتمباشر { get; set; }
        public string دینمباشر { get; set; }
        public int? AksSaheb { get; set; }
        public int? AksMobasher { get; set; }
        public string توضیحات { get; set; }
        public int? مبلغبدهی { get; set; }
        public int? انتقالبهپرونده { get; set; }
        public int? انتقالازپرونده { get; set; }
        public string محلبایگانی { get; set; }
        public bool? محجور { get; set; }
        public bool? غیرفعال { get; set; }
        public bool? تغییرشغل { get; set; }
        public string وبسایت { get; set; }
        public string ایمیل { get; set; }
        public int? EtCode { get; set; }
        public string رشتهتحصیلی { get; set; }
        public string ناحیهشهرداری { get; set; }
        public string فکسمنزل { get; set; }
        public string پلاکپاساژ { get; set; }
        public string حراجازتاریخ { get; set; }
        public string حراجتاتاریخ { get; set; }
        public string فروشفوقالعادهاز { get; set; }
        public string فروشفوقالعادهتا { get; set; }
        public bool? واگذاریااجاره { get; set; }
        public bool? تغییرمکان { get; set; }
        public string قیم { get; set; }
        public string آموزشنظامصنفی { get; set; }
        public string آموزشنظامصنفیمسلسل { get; set; }
        public string شناسهملی { get; set; }
        public string شمارهتاییدبهداشت { get; set; }
        public string تاریختاییدبهداشت { get; set; }
        public string پلاکقدیم { get; set; }
        public string SmsIds { get; set; }
        public string BinaryIds { get; set; }
        public string ناحیهاماکن { get; set; }
        public bool? IsSent { get; set; }
        public DateTime? LastSent { get; set; }
        public string شناسهشیوا { get; set; }
        public string پلاکآبیقدیم { get; set; }
        public string هویت { get; set; }
        public string شهر { get; set; }
        public string مرجعصدور { get; set; }
        public string نوعفروش { get; set; }
        public string مذهب { get; set; }
        public string وضعیتمالکیت { get; set; }
        public string LetterIds { get; set; }
        public string وضعیترسیدگی { get; set; }
        public string مرحله { get; set; }
        public string حراجاز { get; set; }
        public string حراجتا { get; set; }
        public string فوقاز { get; set; }
        public string فوقتا { get; set; }
        public string نامخانوادگیمباشر { get; set; }
        public string رشتهتحصیلیمباشر { get; set; }
        public string بدهیازسال { get; set; }
        public string بدهیتاسال { get; set; }
        public string بازرسیمرحلهاولبازرس { get; set; }
        public string بازرسیمرحلهاولشمارهنامه { get; set; }
        public string بازرسیمرحلهاولنقص { get; set; }
        public string بازرسیمرحلهاولتاریخ { get; set; }
        public string نوعشخص { get; set; }
        public string نوعپروانهکسبقبلی { get; set; }
        public string نواقصبازرسی { get; set; }
        public string تابعیت { get; set; }
        public string نظاموظیفه { get; set; }
        public string شمارهگذرنامه { get; set; }
        public string تاریخگذرنامه { get; set; }
        public string گذرنامهانقضاء { get; set; }
        public string شمارهاقامت { get; set; }
        public string تاریخصدوراقامت { get; set; }
        public string تاریخانقضاءاقامت { get; set; }
        public string شمارهپروانهکار { get; set; }
        public string تاریخپروانهکار { get; set; }
        public string انقضاءپروانهکار { get; set; }
        public string PicSahebPath { get; set; }
        public int? حداقلمساحت { get; set; }
        public string طبقه { get; set; }
        public string واحد { get; set; }
        public string نوعسند { get; set; }
        public string عنوانسند { get; set; }
        public string نوعمالکیت { get; set; }
        public string دهستان { get; set; }
        public string ورثهمحجور { get; set; }
        public string ولیقهری { get; set; }
        public string شمارهقیمنامه { get; set; }
        public string تاریخصدورقیمنامه { get; set; }
        public string مرجعصادرکنندهقیمنامه { get; set; }
        public string نامقیم { get; set; }
        public string کدملیقیم { get; set; }
        public string شمارهشناسنامهقیم { get; set; }
        public string LastUpdate { get; set; }
        public string ناممستعار { get; set; }
        public string نوعشغلقبلی { get; set; }
        public string رستهقبلی { get; set; }
        public string شناسهثبتشرکت { get; set; }
        public bool? IsEdit { get; set; }
        public string کدرهگیری { get; set; }
        public string مباشردارد { get; set; }
        public string شریکدارد { get; set; }
        public string بدهیسالیانه { get; set; }
        public string سریشناسنامه { get; set; }
        public string ادارهبهداشت { get; set; }
        public string PicMobasherPath { get; set; }
        public string دستهتحصیلی { get; set; }
        public string ناممستعارمباشر { get; set; }
        public string کدمعین { get; set; }
        public string کددفترکل { get; set; }
        public string علتغیرفعالپرونده { get; set; }
        public string تاریخغیرفعال { get; set; }
        public string شمارهنامهغیرفعال { get; set; }
        public string علتتعلیق { get; set; }
        public string OrgPictures { get; set; }
        public string صندوقمکانیزه { get; set; }
        public string دستگاهکارتخوان { get; set; }
        public string ترازودیجیتال { get; set; }
        public string دوربینمداربسته { get; set; }
        public bool? Is27 { get; set; }
        public int? ماندهازقبل { get; set; }
        public string شمارهکارتبازرگانی { get; set; }
        public string تاریخکارتبازرگانی { get; set; }
        public string محصولاتصادراتی { get; set; }
        public string نشانیکارخانه { get; set; }
        public string تلفنهایکارخانه { get; set; }
        public string محصولاتمندرجدرپرونده { get; set; }
        public string کمیسیونفرعی { get; set; }
        public string تاریخطرحکمیسیون { get; set; }
        public string تاریخطرحکمیسیونفنی { get; set; }
        public string تاریخطرحکمیسیونهیئتمدیره { get; set; }
        public string تلفنرابط { get; set; }
        public string توضیحاتطرحکمیسیون { get; set; }
        public string توضیحاتطرحکمیسیونفنی { get; set; }
        public string توضیحاتکمیسیونهیئتمدیره { get; set; }
        public string شمارهاولینپروانه { get; set; }
        public string تاریخاولینپروانه { get; set; }
        public string تاریخابطال { get; set; }
        public bool? دخانیات { get; set; }
        public string مساحتانبار { get; set; }
        public string عمدهکالا { get; set; }
        public string تاریخاستعلامدارایی { get; set; }
        public string شمارهاستعلامدارایی { get; set; }
        public bool? پاسخاماکنمثبت { get; set; }
        public bool? پاسخبهداشتمثبت { get; set; }
        public string تاریخانقضاءدرخواست { get; set; }
        public string تاریخمجوزدخانی { get; set; }
        public string انقضاءمجوزدخانی { get; set; }
        public string شمارهمجوزدخانی { get; set; }
        public bool? دارایمجوزدخانی { get; set; }
        public int? آخرینعضویت { get; set; }
        public string آدرسشرکت { get; set; }
        public string سمتشرکت { get; set; }
        public string نوعکاربری { get; set; }
        public string دستگاهها { get; set; }
        public int? شمارهتابلو { get; set; }
        public string توضیحاتتابلو { get; set; }
        public string آدرسواحدصنفیقبلی { get; set; }
        public string مفاصاحسابشهرداری { get; set; }
        public string تاریخمفاصاحساب { get; set; }
        public int? سالآخرینعضویت { get; set; }
        public string شبکهاجتماعی { get; set; }
        public string کلاسهایآموزشی { get; set; }
        public string مسئولپرونده { get; set; }
        public string آخرینبازرسی { get; set; }
        public string مجوزماهرمضان { get; set; }
        public string DeviceId { get; set; }
        public double? Lat { get; set; }
        public double? Lng { get; set; }
        public bool? IsLock { get; set; }
        public string FirebaseToken { get; set; }
        public DateTime? LastFingerPrintDetect { get; set; }
        public string کداقتصادی { get; set; }
        public int? تعدادپروانههایکسب { get; set; }
        public string نوععضویت { get; set; }
        public string سایر { get; set; }
        public string محلثبتشرکت { get; set; }
        public string نامتجاری  { get; set; }
    }
}
